### ISSUE TITLE
Need to raise minimum `cryptography` dependency

### ISSUE THREAD

**Issue by garrett-stevens** [conda-forge/pyopenssl-feedstock#7]
Hello there,

I've been having some problems with SSL certificates, and I think I've traced it to an incompatible combination of `pyopenssl` and `cryptography` (both installed from conda-forge). I think the `meta.yaml` for the current version (17.5.0) of conda-forge's `pyopenssl` has the wrong minimum version specified. If you look at the 17.5.0 release of `pyopenssl` on GitHub, they bumped the minimum `cryptography` version to 2.1.4:
https://github.com/pyca/pyopenssl/blob/d21fcd810317aa7579af0c194a61af377ade7f0e/setup.py#L98
But in this repo, the `meta.yaml` still has the minimum as 1.9:
https://github.com/conda-forge/pyopenssl-feedstock/blob/58797cab4f809b1acfd694a546fee4cb7158fca3/recipe/meta.yaml#L24

Can I just fork, change the minimum version, and submit a PR to fix this? I wasn't sure if there was a build number or something somewhere I also had to update as well.

Thanks!

**Comment by jakirkham** [comment]
Yes please. A PR would be welcome. Thanks for the report and helping out.

**Comment by jakirkham** [comment]
FTR have pulled all the 17.5.0 packages that were deployed with the wrong version number.
